[workspace]
authors = ["Lukasz Czerniawski <l.czerniawski@icloud.com>"]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "crypto"
description = "A Mojo cryptography library intended to cover the commonly used cryptographic algorithms."
license = "MIT"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
readme = "README.md"
version = "0.1.0"

[tasks]
build = "mojo package src/crypto -o crypto.mojopkg"
test = "sh scripts/run_tests.sh"
format = "mojo format src/crypto"
build_rattler = "rattler-build build --recipe conda.recipe/recipe.yaml -c conda-forge -c https://conda.modular.com/max -c https://repo.prefix.dev/modular-community"

[dependencies]
mojo = ">=1.0.0b1,<2"
